Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: true
  # Change the default 80 chars limit value
  Max: 120

Metrics/AbcSize:
  Severity: refactor

Metrics/MethodLength:
  Severity: refactor

Metrics/CyclomaticComplexity:
  Severity: refactor

Metrics/PerceivedComplexity:
  Severity: refactor
