language: shell
sudo: required
services:
- docker
install:
- make build
script:
- make test
deploy:
  provider: rubygems
  api_key:
    secure: mQPoe4gvvxHI/jm80i2mNo6roxMQxXNZXqVnxwzXZuKXsneK7B83oXJOFgj4X9ojQ82YV7GD4Yroo2akfLFfccgmHyBQQj1XNN4vKz1RP5r3jHOiVl95WwlCy9XwS15cNonTb8JGUgfVxXgKhT86etrSVEDFCXnp2UM/A8orx4x8quz4D08Trr+rZHqNkigBmuS8KlIFjGrdoOmxWnmO5LusdFoCDl4ULs5S13QK1/Yp0kBwe1pwzu5BHZbLUGEsbLHmPkawgkRqFHzfxH5Qz2QXQqhC4oDr1JgkpESFdt34Q1crZX9FK3UGHz/FqVYvYM1Kiwq1ES2U5QP7jA7Nts5Fu8K19DHr/0MyJ1z9qm1vyMZ1wfXxCSe8PNtgOCctYmaxT9qxOAhhi4hJ9ftusSA8TsjMv8vVTKyg2meTWV48gj6MTZmRWP8HU2zcEMjrwauANDrbrMeSscTpPGAgGRwlecEaa5KM9gqArg7ZRcQ4tyf5VpYnVxsfS37BUEUhZVqBfn52V2BvWadmeMq4M5/MRFEYeQpOEIUaWwner3/dYWNNnBVowTDmBKcKRbsi3AiHaBMTpCyiOcth8T1UOTRm3uCxgF4tovfr05FZpR7IiBEIo4g4uSt6xeOjk6jSqljPM9XpKgY+sd2OoFMAM4qcT5LmjfBurPTm2IKlbcE=
  on:
    tags: true
